# Learning NumPy

https://youtu.be/lLRBYKwP8GQ

In [1]:
import numpy as np

In [6]:
my_array = np.arange(3,10,.5)
print(my_array)
print(type(my_array))
print(type(my_array[0]))

[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [7]:
from_lst = np.array(['a', 'b', 'c'])
print(from_lst)
print(type(from_lst))
print(type(from_lst[0]))

['a' 'b' 'c']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [5]:
from_num_lst = np.array([1,2,3])
print(type(from_num_lst))
print(type(from_num_lst[0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [20]:
less_space_list = np.array([1,2,127], dtype=np.int8)
print(type(less_space_list[2]))

<class 'numpy.int8'>


In [47]:
#array_2d = np.array([[1, 2, 3], [9, 10, 11]])
array_2d = np.array([np.arange(4), [4,5,6,7]], dtype=np.int8)
print(array_2d)
print(type(array_2d))
print(type(array_2d[0]))
print(type(array_2d[0][0]))

[[0 1 2 3]
 [4 5 6 7]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [48]:
array_2d.shape

(2, 4)

In [49]:
my_array.shape

(14,)

In [50]:
flipped_array_2d = array_2d.reshape(4,2)
print(array_2d)
print('')
print(flipped_array_2d)

[[0 1 2 3]
 [4 5 6 7]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [54]:
print(flipped_array_2d.reshape(8))
print('')
print(flipped_array_2d.reshape(1,8))
print('')
print(flipped_array_2d.reshape(8,1))

[0 1 2 3 4 5 6 7]

[[0 1 2 3 4 5 6 7]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [58]:
empty = np.zeros((2,4))
print(empty)
print(type(empty))
print(type(empty[0][0]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [61]:
ones = np.ones((2,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [63]:
eye = np.eye(3) # "eye" stands for "I" (Identity Matrix)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
eye_k1 = np.eye(3, k=1)
print(eye_k1)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [65]:
eye_kneg1 = np.eye(3, k=-1)
print(eye_kneg1)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [66]:
?np.eye

In [67]:
print(eye[::-1])

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
